M48
; DRILL file {KiCad (6.0.2-0)} date Monday, 21 February 2022 at 07:07:25
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-21T07:07:25+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.4116Y-2.58
T2
X6.25Y-2.75
X6.35Y-2.75
X6.45Y-2.75
X6.55Y-2.75
T0
M30
