M48
; DRILL file {KiCad (6.0.2-0)} date Saturday, 19 February 2022 at 16:59:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-19T16:59:37+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X6.545Y-2.4227
T2
X6.3626Y-2.3795
T3
X6.25Y-2.745
X6.35Y-2.745
X6.45Y-2.745
X6.55Y-2.745
T0
M30
