M48
; DRILL file {KiCad (6.0.5-0)} date Sunday, 08 May 2022 at 16:30:11
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-08T16:30:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.4154Y-2.58
T2
X6.25Y-2.75
X6.35Y-2.75
X6.45Y-2.75
X6.55Y-2.75
T0
M30
